### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by coryrobbins** [coryrobbins/markdown-portfolio#2]
- [ ] Turn on GitHub Pages
- [ ] Outline my portfolio
- [ ] Introduce myself to the world
- [ ] There must be spaces in order for the check list to work!!

**Comment by coryrobbins** [comment]
add check list

**Comment by coryrobbins** [comment]
- [ ] Turn on GitHub Pages
- [ ] Outline my portfolio
- [ ] Introduce myself to the world
